name: Build and Test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          maven-version: '3.8.x'
      - name: Build with Maven
        run: mvn clean install
      - name: Run Tests
        run: mvn test
      - name: Package Spring Boot Application
        run: mvn package -DskipTests
      - name: Run Spring Boot Application
        run: java -jar target/my-spring-boot-app.jar
      - name: Send Notifications
        uses: actions/slack@v3
        with:
          message: 'Build and test completed successfully!'
